### ISSUE TITLE
Improvement request

### ISSUE THREAD

**Issue by rallets** [MPCoreDeveloper/Posseth.NamedArguments.AnalyzerAndFixer#1]
Hi, we would like to use an Analyzer which could help us to enforce some rules about named parameters. 
Then I tried your Analyzer, mentioned in the roslyn repo.

A) Our biggest problem about named parameters are `record` types, that become very confusing with a lot of parameters (for example: mappers).
Do you know if it's possible to config the Analyzer just to look to records? it will solve our needs.

B) We found also annoying that named parameters are enforced to many very common methods. 
One examples:
- Linq `predicate` parameter
- string.IsnullOrEmpty(value: "")

```
.Where(x => !string.IsNullOrWhiteSpace(x))
```
is forced to be
```
.Where(predicate: x => !string.IsNullOrWhiteSpace(value: x))
```
that we find pretty verbose.

C) We found a bug with this code that is not fixed by the fixer:
```
public Uri GetGetPresignedUrl(string objectKey) => new(
    s3Provider.GetGetPresignedUrl(
        bucketName: appConfiguration.Value.Amazon.S3.BucketName,
        objectKey: objectKey,
        expires: timeProvider.GetLocalNow().DateTime.AddHours(value: 24)
    )
);
```

![Image](https://github.com/user-attachments/assets/27f154a0-3da2-44fd-93c7-06f79a3aab8a)

Thank you

**Comment by MPCoreDeveloper** [comment]
Hello Your issues should be solved see the current source and nuget package 1.0.1.1

dotnet add package Posseth.NamedArguments.AnalyzerAndFixer --version 1.0.1.1

Note : restart the IDE after update for the Fixer to initialize

**Comment by rallets** [comment]
Hi, @MPCoreDeveloper thank you for the update, really appreciated it. I finally had time to try the latest 1.0.1.1.

1) I'm not sure it's an improvement yet, because I get still a ton of warnings about arguments that should be named. But I have set the new config option in `.editorconfig`, so I was expecting to get the hint only for records. I still don't get warnings for records, so I'm wondering if I am missing something. I enabled the analyzer only in a project, that have its own `.editorconfig`.
```
# Remove the line below if you want to inherit .editorconfig settings from higher directories
# root = true

# C# files
[*.cs]

# Configure OnlyForRecords option
dotnet_diagnostic.PNA1000.OnlyForRecords = true  # or false

# Configure ExcludedMethodNames option
# dotnet_diagnostic.PNA1000.ExcludedMethodNames = ToString,Equals,GetHashCode
```

![Image](https://github.com/user-attachments/assets/4c7569a4-5790-4c05-968b-b8774a017bc6)

2) Then - if it's technically feasible - I would like to suggest to be able to add to the exclusion list not only the argument name, but also a object/namespace. 
For example, I would like to avoid clashing rules between `System.Linq.Enumerable.Where` and `MyNamespace.Myclass.Where`, so I don't want the warning for the built-in method, but I want them for the custom ones.

**Comment by MPCoreDeveloper** [comment]
Thank you for your clear and  detailed answer , this helps solving the issue fast , also note this time I did get a notification from the system and thus I will solve this a lot faster as the previous . 

I will implement also new tests with nested invocations when the options are set .
